import streamlit as st
import streamlit.components.v1 as components
import httpx
import json
import os
import re
import time
import base64
import pyotp
import qrcode
import io

# Page Configuration
st.set_page_config(
    page_title="Government Welfare Assistant",
    page_icon="🏛️",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# Hide Streamlit default UI elements (Header, Footer, Padding)
st.markdown("""
<style>
    section[data-testid="stSidebar"] { display: none !important; }
    header[data-testid="stHeader"] { display: none !important; }
    footer { display: none !important; }
    .block-container { padding: 0 !important; margin: 0 !important; max-width: 100% !important; }
    .stApp { background-color: #ffffff !important; }
</style>
""", unsafe_allow_html=True)

# Helper function to convert local image files to Base64
def get_image_b64(filename):
    p = os.path.join(os.path.dirname(__file__), filename)
    if os.path.exists(p):
        try:
            with open(p, "rb") as f:
                return f"data:image/png;base64,{base64.b64encode(f.read()).decode()}"
        except Exception:
            pass
    return ""

logo_b64 = get_image_b64("gwa-logo.png")
hero_b64 = get_image_b64("gwa-hero.png")

# EXACT USER UI HTML TEMPLATE (PLAIN STRING TO PREVENT F-STRING SYNTAX ERRORS)
USER_UI_HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Government Welfare Assistant</title>
<style>
@page{size:1024px 1536px;margin:0}
:root{--green:#00865a;--green2:#0a9b68;--navy:#112448;--muted:#5e6f86;--line:#dce5e8;--soft:#f4fbf8;--gold:#e9b84f;--ai:#7770e8;--max:980px}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{zoom:.95;margin:0;background:#fff;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,Arial,sans-serif;color:var(--navy);font-size:13px}button,input{font:inherit}.page{max-width:var(--max);margin:auto;padding:0 0 24px}.top{height:56px;border-bottom:1px solid #e9eeee;display:grid;grid-template-columns:260px 1fr 285px;align-items:center;gap:8px;padding:0 12px}.brand{display:flex;align-items:center;gap:10px}.brand img{height:42px;max-width:245px;display:block;object-fit:contain;object-position:left center}.nav{display:flex;align-items:center;justify-content:center;gap:16px}.nav a{color:var(--navy);text-decoration:none;font-size:12px;padding:16px 0 13px;border-bottom:2px solid transparent;white-space:nowrap;font-weight:600}.nav a.active{color:var(--green);border-bottom-color:var(--green);font-weight:700}.actions{display:flex;gap:8px;align-items:center;justify-content:flex-end}.select,.btn{height:34px;border-radius:8px;border:1px solid var(--line);background:#fff;color:var(--navy);padding:0 16px;cursor:pointer;font-weight:600;font-size:12px}.btn.primary{background:var(--green);color:#fff;border-color:var(--green);font-weight:700}.btn.outline{color:var(--green);border-color:var(--green);font-weight:700}.btn:hover{transform:translateY(-1px);opacity:0.95}
.hero{display:grid;grid-template-columns:1.02fr .98fr;gap:18px;align-items:center;padding:25px 18px 6px}.crumb{font-size:10px;color:#63738a;margin-bottom:8px;font-weight:600}.crumb span{margin:0 5px}.hero h1{font-size:32px;line-height:1.08;margin:0 0 12px;letter-spacing:-.7px;font-weight:900}.hero h1 em{font-style:normal;color:var(--green)}.hero p{font-size:13px;line-height:1.5;color:#435b76;max-width:470px;margin:0 0 18px}.hero-actions{display:flex;gap:11px}.hero-img{width:100%;height:270px;display:block;object-fit:cover;object-position:center;border-radius:8px}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;padding:12px 18px 18px}.stat{display:flex;align-items:center;gap:9px}.stat-icon{width:30px;height:30px;border-radius:50%;background:#e9f7f1;color:var(--green);display:grid;place-items:center;font-size:16px;font-weight:800}.stat strong{display:block;font-size:13px;font-weight:800}.stat small{display:block;color:#66768b;font-size:9px;margin-top:2px}
.ai-box{margin:0 18px 20px;background:#fff;border:1px solid var(--line);border-radius:10px;box-shadow:0 3px 16px rgba(17,36,72,.06);padding:16px}.ai-head{display:flex;align-items:center;gap:10px}.ai-badge{width:30px;height:30px;border-radius:6px;background:#a9a1ff;color:#fff;font-size:16px;font-weight:800;display:grid;place-items:center}.ai-head h2{margin:0;font-size:17px;font-weight:800}.ai-head p{margin:2px 0 0;color:#5f7086;font-size:11px}.ai-top{margin-left:auto;color:#63738a;font-size:11px;cursor:pointer}.ai-input-row{display:grid;grid-template-columns:1fr 90px 100px;gap:10px;margin-top:14px}.ai-input{height:38px;border:1px solid #ccd9df;border-radius:7px;padding:0 14px;color:#1e293b;outline:none;font-size:12px}.ai-input:focus{border-color:var(--green);box-shadow:0 0 0 2px rgba(0,134,90,0.1)}.chips{display:flex;gap:10px;margin-top:12px;flex-wrap:wrap}.chip{border:0;background:#eef8f5;color:#295e51;border-radius:16px;padding:8px 14px;font-size:10px;cursor:pointer;font-weight:600}.chip:hover{background:#dcf2eb}.section{padding:0 18px;margin-bottom:24px}.section-head{display:flex;justify-content:space-between;align-items:flex-end;margin-bottom:12px}.section h2{font-size:18px;margin:0;font-weight:800}.section-sub{margin:3px 0 0;color:#62728a;font-size:11px}.link{color:var(--green);font-weight:700;font-size:11px;text-decoration:none}.categories{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.cat{border:1px solid var(--line);border-radius:8px;background:#fff;padding:12px;display:flex;align-items:center;gap:8px;min-height:60px;cursor:pointer;transition:all .2s ease}.cat:hover{border-color:#a7d9c6;box-shadow:0 4px 12px rgba(0,134,90,.08);transform:translateY(-1px)}.cat-icon{width:32px;height:32px;border-radius:8px;display:grid;place-items:center;font-size:16px;flex:none}.cat:nth-child(4n+1) .cat-icon{background:#e6f8ef;color:#0a8c60}.cat:nth-child(4n+2) .cat-icon{background:#eaf2ff;color:#2372c9}.cat:nth-child(4n+3) .cat-icon{background:#eef8f2;color:#0c8e72}.cat:nth-child(4n) .cat-icon{background:#fff1dc;color:#e88a16}.cat strong{font-size:11px;display:block;font-weight:700}.cat small{font-size:9px;color:#6c7c90;display:block;margin-top:2px}.arrow{margin-left:auto;color:#6e7f93;font-size:14px;font-weight:700}
.steps{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}.step{position:relative;padding:10px 10px 8px;background:#fff;border:1px solid var(--line);border-radius:8px}.step:not(:last-child):after{content:"→";position:absolute;right:-12px;top:28px;color:#9bb8b0;font-weight:700}.num{font-size:18px;color:var(--green);font-weight:900;margin-bottom:12px}.step-icon{width:30px;height:30px;border-radius:50%;background:#eef8f4;color:var(--green);display:grid;place-items:center;margin-bottom:10px;font-weight:800}.step h3{font-size:12px;margin:0 0 5px;font-weight:700}.step p{font-size:10px;line-height:1.4;color:#617188;margin:0}
.feature-grid{display:grid;grid-template-columns:1.08fr .92fr;gap:16px}.feature{border:1px solid var(--line);border-radius:10px;padding:16px;background:#fff;min-height:230px}.feature-title{display:flex;gap:8px;align-items:center}.feature-title .ficon{font-size:20px;color:var(--green)}.feature h3{margin:0;font-size:15px;font-weight:800}.feature>p{margin:3px 0 12px;color:#63738a;font-size:11px}.app-inner{display:grid;grid-template-columns:1.25fr .8fr;gap:12px}.chat{border:1px solid #e0e7ec;border-radius:8px;padding:10px;background:#fbfcfd}.bubble{padding:9px;border-radius:7px;background:#f0f4f8;margin-bottom:8px;font-size:10px;line-height:1.4}.bubble.user{background:#d9f8e6;text-align:right}.bubble.success{background:#f0f4f8}.progress{border-left:1px solid #edf0f2;padding-left:12px}.progress h4{font-size:10px;margin:0 0 10px;font-weight:700}.prog-row{display:flex;justify-content:space-between;font-size:10px;padding:8px 0;border-bottom:1px solid #edf0f2}.ok{color:var(--green);font-weight:800}.doc-inner{display:grid;grid-template-columns:130px 1fr;gap:14px}.doc-thumb{border:1px solid #dfe6e9;border-radius:6px;padding:8px;height:145px;background:#fafafa}.paper{height:100%;background:repeating-linear-gradient(to bottom,#fff 0,#fff 9px,#e7ebee 10px);border:1px solid #ddd}.extract{padding:2px 0}.extract h4{font-size:11px;color:#00764f;margin:0 0 8px;font-weight:700}.field{display:flex;justify-content:space-between;font-size:10px;margin:0 0 10px}.good{color:#07855b;font-weight:700}.warn{color:#e38a00;font-weight:700}.mini-btn{margin-top:10px;height:32px;border:1px solid var(--green);background:#fff;color:var(--green);border-radius:6px;padding:0 14px;font-size:11px;font-weight:700;cursor:pointer}
.recs{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.scheme{border:1px solid var(--line);border-radius:9px;padding:14px;min-height:180px;background:#fff}.scheme h3{font-size:13px;margin:0 0 4px;color:#0b7e59;font-weight:800}.scheme .min{font-size:9px;color:#66768a}.scheme p{font-size:10px;line-height:1.4;margin:10px 0;color:#334155}.tags{display:flex;gap:6px;flex-wrap:wrap}.tag{font-size:8px;padding:4px 8px;border-radius:4px;background:#edf3f5;color:#40536b;font-weight:600}.scheme-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:14px}.scheme-actions button{height:30px;border-radius:6px;font-size:9px;font-weight:700;cursor:pointer}.scheme-actions .primary{background:var(--green);color:#fff;border:1px solid var(--green)}.scheme-actions .secondary{background:#fff;color:var(--green);border:1px solid var(--green)}
.banner{margin:20px 18px 10px;background:#e9f8f0;min-height:96px;border-radius:10px;display:grid;grid-template-columns:1.6fr 1fr;gap:14px;align-items:center;padding:20px 28px;position:relative;overflow:hidden}.banner h2{font-size:18px;margin:0 0 6px;font-weight:900}.banner p{font-size:11px;color:#527064;margin:0}.banner-art{position:absolute;left:0;right:38%;bottom:-16px;height:68px;opacity:.45;background:linear-gradient(90deg,transparent,#cfe7d7,transparent);border-radius:50%}.banner-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;position:relative}.bstat{background:#fff;border:1px solid #e4e9e8;border-radius:6px;text-align:center;padding:10px 4px}.bstat strong{display:block;color:#006e4e;font-size:14px;font-weight:800}.bstat small{font-size:8px;color:#66768a}
.footer{border-top:1px solid #e4e8eb;padding:16px 18px 0;display:grid;grid-template-columns:1fr auto;gap:20px;align-items:center;margin-top:20px}.footbrand{display:flex;align-items:center;gap:8px}.footbrand img{height:38px}.footlinks{display:flex;gap:18px;font-size:10px;font-weight:600}.footlinks a{color:#43536a;text-decoration:none}.copyright{grid-column:1/-1;border-top:1px solid #edf0f2;padding-top:10px;margin-top:10px;color:#718096;font-size:9px;display:flex;justify-content:space-between}
.modal-backdrop{position:fixed;inset:0;background:rgba(11,30,52,.45);display:none;align-items:center;justify-content:center;z-index:100}.modal-backdrop.open{display:flex}.modal{width:min(440px,calc(100vw - 30px));background:#fff;border-radius:12px;border:1px solid var(--line);box-shadow:0 18px 55px rgba(17,36,72,.18);padding:24px;position:relative}.modal-close{position:absolute;right:14px;top:10px;border:0;background:none;font-size:24px;color:#607086;cursor:pointer}.modal h2{margin:0 0 7px;font-size:20px;font-weight:800}.modal p{color:#63738a;font-size:11px;line-height:1.5}.modal input,.modal select{width:100%;height:38px;border:1px solid #ccd9df;border-radius:7px;padding:0 12px;margin:6px 0 12px;font-size:12px}.modal .full{width:100%;margin-top:8px;height:38px;font-size:12px}.modal .choice{display:grid;grid-template-columns:1fr 1fr;gap:8px}.toast{position:fixed;right:20px;bottom:20px;background:#10243c;color:#fff;padding:12px 16px;border-radius:8px;font-size:11px;opacity:0;transform:translateY(8px);transition:.2s;pointer-events:none;z-index:200}.toast.show{opacity:1;transform:none}
@media(max-width:900px){.top{height:auto;padding:10px 0;flex-wrap:wrap}.brand img{max-width:220px}.nav{order:3;width:100%;justify-content:center;gap:15px}.hero{grid-template-columns:1fr;padding-top:20px}.hero-img{max-height:300px;object-fit:cover}.categories{grid-template-columns:repeat(2,1fr)}.feature-grid{grid-template-columns:1fr}.recs{grid-template-columns:1fr}.steps{grid-template-columns:repeat(2,1fr)}.step:not(:last-child):after{display:none}.page{padding:0 16px}.stats{padding-left:0;padding-right:0}}
</style>
</head>
<body>
<div class="page" id="home">
<header class="top">
  <div class="brand"><img src="__LOGO_B64__" alt="Government Welfare Assistant"></div>
  <nav class="nav"><a href="#home" class="active">Home</a><a href="#explore">Explore Schemes</a><a href="#journey">My Welfare Journey</a><a href="#resources">Resources</a></nav>
  <div class="actions"><button class="select">English ▾</button><button class="btn outline" onclick="auth('Sign In')">Sign In</button><button class="btn primary" onclick="auth('Create Account')">Create Account</button></div>
</header>
<main>
<section class="hero">
 <div><div class="crumb">Citizens <span>|</span> Schemes <span>|</span> AI <span>|</span> A Stronger Tomorrow</div><h1>Find Government Support<br>That Fits <em>Your Situation</em></h1><p>Tell us what you need. Our AI helps you discover relevant government schemes, understand eligibility and prepare your application.</p><div class="hero-actions"><button class="btn primary" onclick="journey()">Start My Welfare Journey →</button><button class="btn outline" onclick="go('explore')">Explore Schemes</button></div></div>
 <div><img class="hero-img" src="__HERO_B64__" alt="Family using Government Welfare Assistant"></div>
</section>
<section class="stats"><div class="stat"><div class="stat-icon">🏛️</div><div><strong>46+</strong><small>Central &amp; State Sources</small></div></div><div class="stat"><div class="stat-icon">📑</div><div><strong>120+</strong><small>Indexed Schemes</small></div></div><div class="stat"><div class="stat-icon">🌐</div><div><strong>3</strong><small>Languages Supported</small></div></div></section>
<section class="ai-box" id="assistant"><div class="ai-head"><div class="ai-badge">AI</div><div><h2>Ask the Welfare Assistant</h2><p>Tell us what you need in your own words. You can type or speak.</p></div><div class="ai-top" onclick="fill('I need financial support for higher education')">↻ &nbsp; Try example</div></div><div class="ai-input-row"><input id="aiInput" class="ai-input" placeholder="e.g., I am looking for financial assistance for my education..."><button class="btn outline" onclick="speak()">🎙 Speak</button><button class="btn primary" onclick="searchAI()">🔍 Search</button></div><div class="chips"><button class="chip" onclick="fill('I need a scholarship')">🎓 I need a scholarship</button><button class="chip" onclick="fill('Looking for housing support')">🏠 Looking for housing support</button><button class="chip" onclick="fill('Farmer financial assistance')">🌾 Farmer financial assistance</button><button class="chip" onclick="fill('Scheme eligibility for my family')">👨‍👩‍👧 Scheme eligibility for my family</button></div></section>
<section class="section" id="explore"><div class="section-head"><div><h2>Explore Government Support</h2><p class="section-sub">Browse schemes by category or explore all schemes</p></div><a class="link" href="#recommendations">View All Categories →</a></div><div class="categories">
<div class="cat" onclick="category('Agriculture & Rural')"><div class="cat-icon">🌾</div><div><strong>Agriculture &amp; Rural</strong><small>12 Schemes</small></div><span class="arrow">→</span></div><div class="cat" onclick="category('Education & Learning')"><div class="cat-icon">🎓</div><div><strong>Education &amp; Learning</strong><small>14 Schemes</small></div><span class="arrow">→</span></div><div class="cat" onclick="category('Health & Wellness')"><div class="cat-icon">💚</div><div><strong>Health &amp; Wellness</strong><small>8 Schemes</small></div><span class="arrow">→</span></div><div class="cat" onclick="category('Housing & Shelter')"><div class="cat-icon">🏠</div><div><strong>Housing &amp; Shelter</strong><small>6 Schemes</small></div><span class="arrow">→</span></div><div class="cat" onclick="category('Employment & Skills')"><div class="cat-icon">💼</div><div><strong>Employment &amp; Skills</strong><small>10 Schemes</small></div><span class="arrow">→</span></div><div class="cat" onclick="category('Women & Child Welfare')"><div class="cat-icon">👩</div><div><strong>Women &amp; Child Welfare</strong><small>9 Schemes</small></div><span class="arrow">→</span></div><div class="cat" onclick="category('Social Welfare')"><div class="cat-icon">🤝</div><div><strong>Social Welfare</strong><small>7 Schemes</small></div><span class="arrow">→</span></div><div class="cat" onclick="category('Financial Assistance')"><div class="cat-icon">💰</div><div><strong>Financial Assistance</strong><small>11 Schemes</small></div><span class="arrow">→</span></div><div class="cat" onclick="category('Insurance & Security')"><div class="cat-icon">🛡️</div><div><strong>Insurance &amp; Security</strong><small>5 Schemes</small></div><span class="arrow">→</span></div><div class="cat" onclick="category('Business & Entrepreneurship')"><div class="cat-icon">📊</div><div><strong>Business &amp; Entrepreneurship</strong><small>8 Schemes</small></div><span class="arrow">→</span></div></div></section>
<section class="section" id="journey"><div class="section-head"><div><h2>How It Works</h2><p class="section-sub">Get from discovery to application in four simple steps</p></div><a class="link" href="#resources">Learn more →</a></div><div class="steps"><div class="step"><div class="num">01</div><div class="step-icon">👤</div><h3>Tell us about yourself</h3><p>Answer a quick profile or speak to the AI.</p></div><div class="step"><div class="num">02</div><div class="step-icon">🔍</div><h3>Find relevant schemes</h3><p>Get personalized scheme recommendations.</p></div><div class="step"><div class="num">03</div><div class="step-icon">📝</div><h3>Check eligibility</h3><p>AI evaluates your eligibility based on official rules.</p></div><div class="step"><div class="num">04</div><div class="step-icon">🚀</div><h3>Prepare your application</h3><p>Pre-fill forms with AI and required documents.</p></div></div></section>
<section class="feature-grid section" id="resources"><div class="feature"><div class="feature-title"><span class="ficon">✦</span><div><h3>AI Application Assistant</h3><p>Get step-by-step help to complete your application</p></div></div><div class="app-inner"><div class="chat"><div class="bubble"><b>AI Assistant:</b> What is your annual family income?</div><div class="bubble user">You: ₹3,00,000</div><div class="bubble success"><b>AI Assistant:</b> Got it. Added ₹3,00,000 to your application draft.<br><span class="ok">✓ Income captured</span></div><button class="btn primary" style="margin-top:8px" onclick="applyAI()">Try Apply with AI →</button></div><div class="progress"><h4>Application Progress</h4><div class="prog-row">Profile <span class="ok">●</span></div><div class="prog-row">Documents <span>3/4</span></div><div class="prog-row">Application <span>60%</span></div><div class="prog-row">Review <span>○</span></div></div></div></div>
<div class="feature"><div class="feature-title"><span class="ficon">📄</span><div><h3>Understand Your Documents with AI</h3><p>Upload a document and we'll extract key information</p></div></div><div class="doc-inner"><div class="doc-thumb"><div class="paper"></div></div><div class="extract"><h4>Extracted Information</h4><div class="field"><span>Full Name: <b>Arun Kumar</b></span><span class="good">✓ Verified</span></div><div class="field"><span>Date of Birth: <b>12 Aug 1998</b></span><span class="good">✓ Verified</span></div><div class="field"><span>District: <b>Madurai, Tamil Nadu</b></span><span class="warn">⚠ Verify</span></div></div></div><button class="mini-btn" onclick="documentAI()">Upload Document</button></div></section>
<section class="section" id="recommendations"><div class="section-head"><div><h2>Recommended for You</h2><p class="section-sub">Based on your profile and interests</p></div><a class="link" href="#explore">View All Schemes →</a></div><div class="recs"><div class="scheme"><h3>Pradhan Mantri Awas Yojana (Urban)</h3><div class="min">Ministry of Housing and Urban Affairs</div><p>Financial assistance of up to ₹2.67 Lakh for first-time pucca house construction for EWS/LIG families.</p><div class="tags"><span class="tag">Housing</span><span class="tag">Urban</span><span class="tag">Central Scheme</span></div><div class="scheme-actions"><button class="primary" onclick="scheme('Pradhan Mantri Awas Yojana (Urban)')">View Scheme →</button><button class="secondary" onclick="eligibility()">Check Eligibility</button></div></div><div class="scheme"><h3>PM Scholarship Scheme</h3><div class="min">Ministry of Education</div><p>Financial assistance for meritorious students from low-income families.</p><div class="tags"><span class="tag">Education</span><span class="tag">Students</span><span class="tag">Central Scheme</span></div><div class="scheme-actions"><button class="primary" onclick="scheme('PM Scholarship Scheme')">View Scheme →</button><button class="secondary" onclick="eligibility()">Check Eligibility</button></div></div><div class="scheme"><h3>Ayushman Bharat</h3><div class="min">Ministry of Health &amp; Family Welfare</div><p>Health coverage support for eligible families.</p><div class="tags"><span class="tag">Health</span><span class="tag">Family</span><span class="tag">Central Scheme</span></div><div class="scheme-actions"><button class="primary" onclick="scheme('Ayushman Bharat')">View Scheme →</button><button class="secondary" onclick="eligibility()">Check Eligibility</button></div></div></div></section>
<section class="banner"><div><h2>A More Inclusive India<br>Through Informed Citizens</h2><p>Bridging citizens to government support with the power of AI.</p></div><div class="banner-stats"><div class="bstat"><strong>46+</strong><small>Government Sources</small></div><div class="bstat"><strong>120+</strong><small>Schemes Indexed</small></div><div class="bstat"><strong>3</strong><small>Languages</small></div><div class="bstat"><strong>24/7</strong><small>AI Support</small></div></div><div class="banner-art"></div></section>
</main>
<footer class="footer"><div class="footbrand"><img src="__LOGO_B64__" alt="Government Welfare Assistant"></div><div class="footlinks"><a href="#">About</a><a href="#journey">How it works</a><a href="#explore">Explore Schemes</a><a href="#">Privacy</a><a href="#">Security</a><a href="#">Accessibility</a><a href="#">Contact</a></div><div class="copyright"><span>© 2024 Government Welfare Assistant. All rights reserved.</span><span>Built with AI for a Better Tomorrow →</span></div></footer>
</div>
<div class="modal-backdrop" id="modal"><div class="modal"><button class="modal-close" onclick="closeModal()">×</button><div id="modalContent"></div></div></div>
<input type="file" id="fileInput" accept=".pdf,.jpg,.jpeg,.png" hidden onchange="filePicked(this)">
<div class="toast" id="toast"></div>
<script>
function toast(t){const e=document.getElementById('toast');e.textContent=t;e.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>e.classList.remove('show'),2200)}
function go(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth'})}
function fill(t){document.getElementById('aiInput').value=t;document.getElementById('aiInput').focus()}
function searchAI(){const q=document.getElementById('aiInput').value.trim();if(!q){toast('Tell me what support you need first.');return}toast('AI search started: '+q);setTimeout(()=>go('recommendations'),250)}
function speak(){toast('Voice assistant opened. Connect this button to your existing speech service.')}function category(c){toast('Opening '+c+' schemes…');go('recommendations')}function openModal(html){document.getElementById('modalContent').innerHTML=html;document.getElementById('modal').classList.add('open')}function closeModal(){document.getElementById('modal').classList.remove('open')}
function auth(p){openModal('<h2>'+p+'</h2><p>'+(p==='Sign In'?'Sign in to continue your welfare journey.':'Create your personalized welfare account.')+'</p><input placeholder="Email / Mobile"><input type="password" placeholder="Password"><button class="btn primary full" onclick="toast(\'Authentication flow ready\');closeModal()">Continue</button><p style="font-size:10px; color:#64748b; margin-top:8px;">Demo Citizen: citizen.demo@welfare.local | CitizenDemo@123!<br>Demo Admin: admin.demo@welfare.local | AdminDemo@123!</p>')}
function journey(){openModal('<h2>Start My Welfare Journey</h2><p>Answer a few questions and the assistant will help identify relevant support.</p><button class="btn primary full" onclick="closeModal();toast(\'Journey started\');go(\'assistant\')">Start journey</button>')}
function applyAI(){openModal('<h2>Apply with AI</h2><p>The assistant will guide you through the application, reuse confirmed profile information and prepare a draft for your review.</p><button class="btn primary full" onclick="closeModal();toast(\'Application assistant opened\')">Continue</button>')}
function documentAI(){document.getElementById('fileInput').click()}
function filePicked(input){if(input.files.length){toast('Document received: '+input.files[0].name);setTimeout(()=>openModal('<h2>Document details</h2><p>AI extraction completed for the uploaded document.</p><div class="field"><span>Full Name</span><b>Arun Kumar</b></div><div class="field"><span>District</span><b>Madurai, Tamil Nadu</b></div><button class="btn primary full" onclick="closeModal()">Review and confirm</button>'),300)}}
function scheme(n){openModal('<h2>'+n+'</h2><p><b>Benefits</b><br>View the official scheme benefit, eligibility requirements, documents and application process here.</p><div class="choice"><button class="btn outline" onclick="eligibility()">Check Eligibility</button><button class="btn primary" onclick="applyAI()">Apply with AI</button></div>')}
function eligibility(){openModal('<h2>Check Eligibility</h2><p>Question 1 of 4</p><p><b>What is your age?</b></p><input type="number" placeholder="Enter age"><button class="btn primary full" onclick="toast(\'Eligibility answer saved\');closeModal()">Continue →</button>')}
</script>
</body>
</html>"""

final_html = USER_UI_HTML_TEMPLATE.replace("__LOGO_B64__", logo_b64).replace("__HERO_B64__", hero_b64)

# Render the exact user HTML UI inside Streamlit
components.html(final_html, height=2200, scrolling=True)
